### ISSUE TITLE
Tests - status?

### ISSUE THREAD

**Issue by arthurpsmith** [google/abstracttext#7]
I've been exploring the "test" features in functions (the lists under Z8K3). I tentatively added a section to display the tests in AbstractTextContent.php for example. However, I'm trying to figure out if how to run a test against an implementation - it looks like they are all run in eneyj/src/scripts/measure.js? I'm thinking of setting up something to try calling a test (or all tests) in the UI so is that a good place to start?

**Comment by vrandezo** [comment]
Yes, that's currently the only place that calls the tests in Z8K3. It would be awesome to refactor that (or write it fresh) so that you can use it from the UI and be called there. But yes, that's the right approach.

The nice thing is, once calling the tests is factored out, it should not only be included into the UI, but it can also be made easily calleable by a script of its own, and also from the main testing system of eneyj, so that these tests become an integral part of the testing when developing eneyj. I have run a few times into the problem that I broke implementations without noticing because I didn't run the measure script.

**Comment by arthurpsmith** [comment]
Ok, see pull request #8 !
